[package]
name = "llvm-example"
version = "0.1.0"
authors = ["Arrvindh Shriraman <ashriram@cs.sfu.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
llvm-sys = "90.0.0"
peg = "0.6.2"

