#Name=gpu Type=h200 File=/dev/nvidia[0-3]
NodeName=profali Name=gpu Type=h200 File=/dev/nvidia0
NodeName=profali Name=shard Count=8 File=/dev/nvidia0
NodeName=profashriram Name=gpu Type=h200 File=/dev/nvidia1
NodeName=profashriram Name=shard Count=8 File=/dev/nvidia1
NodeName=profrichard Name=gpu Type=h200 File=/dev/nvidia2
NodeName=profrichard Name=shard Count=8 File=/dev/nvidia2
NodeName=profivan Name=gpu Type=h200 File=/dev/nvidia3
NodeName=profivan Name=shard Count=8 File=/dev/nvidia3