ClusterName=research
SlurmctldHost=rcg-psaeedi-1

TaskProlog=/etc/slurm/taskprolog.sh

# --- Scheduling: cons_tres is REQUIRED for per-GPU (--gres / --gpus) ---
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

# --- GPUs as a generic resource ---
GresTypes=gpu,shard

# --- cgroup-based isolation & tracking ---
ProctrackType=proctrack/cgroup
TaskPlugin=task/cgroup,task/affinity

# --- daemons / state ---
SlurmctldPidFile=/var/run/slurm-llnl/slurmctld.pid
#SlurmdPidFile=/var/run/slurm-llnl/slurmd.pid
#SlurmdSpoolDir=/var/spool/slurmd
StateSaveLocation=/var/spool/slurmctld
SlurmUser=slurm
AuthType=auth/munge

# --- logging ---
SlurmctldLogFile=/var/log/slurm/slurmctld.log
#SlurmdLogFile=/var/log/slurm/slurmd.log
SlurmdSpoolDir=/var/spool/slurmd/%n
SlurmdPidFile=/var/run/slurm-llnl/slurmd-%n.pid
SlurmdLogFile=/var/log/slurm/slurmd-%n.log

AccountingStorageType=accounting_storage/slurmdbd
AccountingStorageHost=rcg-psaeedi-1
AccountingStorageTRES=gres/gpu
AccountingStorageEnforce=associations,limits,qos
JobAcctGatherType=jobacct_gather/cgroup

#NodeName=H200 NodeHostName=rcg-psaeedi-1 CPUs=384 Boards=1 SocketsPerBoard=2 CoresPerSocket=96 ThreadsPerCore=2 RealMemory=1540000 Gres=gpu:h200:4
NodeName=profali NodeHostname=rcg-psaeedi-1 Port=6011 CPUs=96 RealMemory=365000 Gres=gpu:h200:1,shard:8 State=UNKNOWN
NodeName=profashriram NodeHostname=rcg-psaeedi-1 Port=6012 CPUs=96 RealMemory=365000 Gres=gpu:h200:1,shard:8 State=UNKNOWN
NodeName=profrichard NodeHostname=rcg-psaeedi-1 Port=6013 CPUs=96 RealMemory=365000 Gres=gpu:h200:1,shard:8 State=UNKNOWN
NodeName=profivan NodeHostname=rcg-psaeedi-1 Port=6014 CPUs=96 RealMemory=365000 Gres=gpu:h200:1,shard:8 State=UNKNOWN


# --- partition ---
PartitionName=profali Nodes=profali State=UP MaxTime=3-00:00:00 AllowAccounts=profa DefCpuPerGPU=8 DefMemPerCPU=2048
PartitionName=profivan Nodes=profivan State=UP MaxTime=3-00:00:00 AllowAccounts=profb DefCpuPerGPU=8 DefMemPerCPU=2048
PartitionName=profrichard Nodes=profrichard State=UP MaxTime=3-00:00:00 AllowAccounts=profc DefCpuPerGPU=8 DefMemPerCPU=2048
PartitionName=profashriram Nodes=profashriram State=UP MaxTime=3-00:00:00 AllowAccounts=profd DefCpuPerGPU=8 DefMemPerCPU=2048

#PartitionName=train Nodes=ALL State=UP MaxTime=INFINITE AllowAccounts=staff \
#  PriorityTier=100 DefCpuPerGPU=96


#PartitionName=gpu Nodes=H200 Default=YES MaxTime=INFINITE State=UP \
#  DefCpuPerGPU=24 DefMemPerCPU=4096 MaxMemPerCPU=8192
